FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    minio==7.2.7 \
    pandas==2.2.2 \
    pyarrow==16.1.0

COPY store_to_minio.py /app/store_to_minio.py

CMD ["python", "/app/store_to_minio.py"]
