FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    streamlit==1.35.0 \
    plotly==5.22.0 \
    pandas==2.2.2 \
    minio==7.2.7 \
    pyarrow==16.1.0

COPY app.py /app/app.py

CMD ["streamlit", "run", "/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
